Description: >
  This template illustrates how to use AWS CodeBuild and AWS CodePipeline to
  achieve continuous deployment of source code from a GitHub repository via a
  Docker container to an Amazon EC2 Container Service cluster.
#ecs-ethereum-network-node-

Parameters:
  GitHubUser:
    Type: String
    Description: Your username on GitHub.

  GitHubRepo:
    Type: String
    Default: ecs-demo-php-simple-app
    Description: The repo name of the sample service.

  GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  BeGaspSqsPaymentWorkerGitHubUser:
    Type: String
    Description: Your username on GitHub.

  BeGaspSqsPaymentWorkerGitHubRepo:
    Type: String
    Default: BeGaspSqsPaymentWorker
    Description: The repo name of the sample service.

  BeGaspSqsPaymentWorkerGitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  ecs-ethereum-network-node-GitHubUser:
    Type: String
    Description: Your username on GitHub.

  ecs-ethereum-network-node-GitHubRepo:
    Type: String
    Default: BeGaspSqsPaymentWorker
    Description: The repo name of the sample service.

  ecs-ethereum-network-node-GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  GitHubToken:
    Type: String
    Description: >
      Token for the user specified above. (https://github.com/settings/tokens)


Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      BeGaspSqsPaymentWorkerGitHubUser:
        default: "User"
      BeGaspSqsPaymentWorkerGitHubRepo:
        default: "Repo"
      BeGaspSqsPaymentWorkerGitHubBranch:
        default: "Branch"
      ecs-ethereum-network-node-GitHubUser:
        default: "User"
      ecs-ethereum-network-node-GitHubRepo:
        default: "Repo"
      ecs-ethereum-network-node-GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal Access Token"
    ParameterGroups:
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken
          - BeGaspSqsPaymentWorkerGitHubRepo
          - BeGaspSqsPaymentWorkerGitHubBranch
          - BeGaspSqsPaymentWorkerGitHubUser
          - ecs-ethereum-network-node-GitHubRepo
          - ecs-ethereum-network-node-GitHubBranch
          - ecs-ethereum-network-node-GitHubUser

Resources:
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/ecs-cluster.yaml
      Parameters:
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  StagingCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/infrastructure/staging/ecs-cluster.yaml
      Parameters:
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/services/ecs/ecs-demo-php-simple-app/deployment-pipeline.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        StagingCluster: !GetAtt StagingCluster.Outputs.ClusterName
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        TemplateBucket: !Sub ecs-begasp-continuous-deployment-${AWS::Region}

  BeGaspSqsPaymentWorkerDeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/services/ecs/BeGaspSqsPaymentWorker/deployment-pipeline.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        BeGaspSqsPaymentWorkerGitHubUser: !Ref BeGaspSqsPaymentWorkerGitHubUser
        GitHubToken: !Ref GitHubToken
        BeGaspSqsPaymentWorkerGitHubRepo: !Ref BeGaspSqsPaymentWorkerGitHubRepo
        BeGaspSqsPaymentWorkerGitHubBranch: !Ref BeGaspSqsPaymentWorkerGitHubBranch
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        TemplateBucket: !Sub ecs-begasp-continuous-deployment-${AWS::Region}

  EcsEthereumNetworkNodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/services/ecs/ecs-ethereum-network-node/deployment-pipeline.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        BeGaspSqsPaymentWorkerGitHubUser: !Ref ecs-ethereum-network-node-GitHubUser
        GitHubToken: !Ref GitHubToken
        BeGaspSqsPaymentWorkerGitHubRepo: !Ref ecs-ethereum-network-node-GitHubRepo
        BeGaspSqsPaymentWorkerGitHubBranch: !Ref ecs-ethereum-network-node-GitHubBranch
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        TemplateBucket: !Sub ecs-begasp-continuous-deployment-${AWS::Region}

  SqsQueues:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/infrastructure/production/sqs.yaml

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/load-balancer.yaml
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ecs-begasp-continuous-deployment-us-east-1/templates/vpc.yaml
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        Subnet1CIDR: 10.215.10.0/24
        Subnet2CIDR: 10.215.20.0/24


Outputs:
  TestRpcServiceUrl:
    Description: The sample service that is being continuously deployed.
    Value: !GetAtt LoadBalancer.Outputs.TestRpcServiceUrl

  TestRpcPipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.TestRpcPipelineUrl

#  BeGaspSqsPaymentWorkerPipelineUrl:
#    Description: The continuous deployment pipeline in the AWS Management Console.
#    Value: !GetAtt BeGaspSqsPaymentWorkerDeploymentPipeline.Outputs.BeGaspSqsPaymentWorkerPipelineUrl
