Resources:
  queueErrorHandling:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: '0'
      MaximumMessageSize: '262144'
      MessageRetentionPeriod: '345600'
      ReceiveMessageWaitTimeSeconds: '0'
      VisibilityTimeout: '30'
